name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v4

      # Login to "owntube" organization on Docker Hub
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and test PeerTube 5.2 image as tag "v521"
      - name: Pull the `owntube/peertube-runner:v521` Docker image if it exists
        run: docker pull owntube/peertube-runner:v521 || true
      - name: Build the `owntube/peertube-runner:v521` Docker image
        run: docker buildx build . --platform linux/amd64 --file Dockerfile.bullseye --tag owntube/peertube-runner:v521
      - name: Test the `owntube/peertube-runner:v521` Docker image
        run: docker run -i --rm --name v521-runner-help owntube/peertube-runner:v521 peertube-runner --help

      # Build and test PeerTube 6.3.2 image as tag "v632"
      - name: Pull the `owntube/peertube-runner:v632` Docker image if it exists
        run: docker pull owntube/peertube-runner:v632 || true
      - name: Build the `owntube/peertube-runner:v632` Docker image
        run: docker buildx build . --platform linux/amd64 --file Dockerfile.bookworm --tag owntube/peertube-runner:v632
      - name: Test the `owntube/peertube-runner:v632` Docker image
        run: docker run -i --rm --name v632-runner-help owntube/peertube-runner:v632 npx peertube-runner --help

      # Push image tags "v521", "v632" and "latest"
      - name: Push the `owntube/peertube-runner:v521` Docker image
        run: docker push owntube/peertube-runner:v521
      - name: Push the `owntube/peertube-runner:v632` Docker image
        run: docker push owntube/peertube-runner:v632
      - name: Push the `owntube/peertube-runner:latest` Docker image
        run: docker tag owntube/peertube-runner:v632 owntube/peertube-runner:latest && docker push owntube/peertube-runner:latest

      # Logout, as logout=true from `docker/login-action@v3` does not seem to work
      - run: docker logout index.docker.io
